### ISSUE TITLE
Don't align patterns and arrows in cases/matches

### ISSUE THREAD

**Issue by garyb** [ianbollinger/purescript-style-guide#3]
e.g. don't do this:

``` purescript
instance semigroupMaybe :: Semigroup a => Semigroup (Maybe a) where
  append Nothing  y        = y
  append x        Nothing  = x
  append (Just x) (Just y) = Just (x <> y)
```

**Comment by soupi** [comment]
Also, I'd like to suggest to avoid using pattern matching in functions and prefer using case instead.
At least for the reason that it is DRYer, when changing the name of a function you don't have to change all cases.

**Comment by ianbollinger** [comment]
@soupi, I personally agree with that rule, but I don't know how contentious it is.

**Comment by garyb** [comment]
I mostly use case now too (especially since `case _ of` was introduced) but there are still a few situations where "equational style" is more pleasant - probably one being where you're matching multiple patterns, as the multi-case is kinda weird.
